FROM iojs:@version
MAINTAINER Andre Ferreira <andrehrf@gmail.com>

RUN mkdir /app
ENV HOME=/app

COPY package.json $HOME
WORKDIR $HOME
RUN npm install --progress=false

COPY . $HOME

CMD ["npm", "start"]