FROM golang:@version
MAINTAINER Andre Ferreira <andrehrf@gmail.com>

RUN id -u app &>/dev/null || useradd --user-group --create-home --shell /bin/false app
ENV HOME=/home/app
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME

USER root
COPY . $HOME
RUN chown -R app:app $HOME/*
USER app

CMD ["go", "run", "app"]